### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by gpbdev1** [howtographql/react-relay#1]
I have run through all the steps in the README but this example does not work. There are issues with the user sign in and sign up mutations. Will this be fixed?

**Comment by marktani** [comment]
Hey, what error messages do you receive? At what step do you receive them?

**Comment by nikolasburk** [comment]
Ah! I think this is because the README doesn't tell to enable the email-password authentication provider in the Graphcool console - should be a quick fix. You can find info how to do this in this chapter: https://www.howtographql.com/react-relay/5-authentication/

I'll update the README with the required instructions soon, thanks for the hint!

**Comment by nikolasburk** [comment]
Just added instructions to README how to enable the auth provider. Thanks again for pointing this out! @gpbdev1 🙌

**Comment by gpbdev1** [comment]
Great thanks! Sorry I was a bit vague, it was late haha. I will test again
soon.
